language: generic
# super user permisions
sudo: required

#env on the travis
services:
  - docker
#build step
before_install:
  - docker build -t 0rtem/docker-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 0rtem/docker-react-test npm run test -- --coverage

after_success:
  - docker built -t 0rtem/multi-client ./client
  - docker built -t 0rtem/multi-nginx ./nginx
  - docker built -t 0rtem/multi-server ./server
  - docker built -t 0rtem/multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  # push to dockerhub
  - docker push 0rtem/multi-client
  - docker push 0rtem/multi-nginx
  - docker push 0rtem/multi-server
  - docker push 0rtem/multi-worker
